//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppVeiculosAntigos.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.ModelConfiguration.Conventions;
    public partial class VeiculosAntigosEntities : DbContext
    {
        public VeiculosAntigosEntities()
            : base("name=VeiculosAntigosEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {

            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();

            Database.SetInitializer<VeiculosAntigosEntities>(null);
        }

        public virtual DbSet<TbFabricante> TbFabricante { get; set; }
        public virtual DbSet<TbTipoDeVeiculo> TbTipoDeVeiculo { get; set; }
        public virtual DbSet<TbVeiculo> TbVeiculo { get; set; }
    }
}
