//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppVeiculosAntigos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbVeiculo
    {
        public int ID { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> AnoFabricao { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> IdFabricante { get; set; }
        public Nullable<int> IdTipoVeiculo { get; set; }
    
        public virtual TbFabricante TbFabricante { get; set; }
        public virtual TbTipoDeVeiculo TbTipoDeVeiculo { get; set; }
    }
}
